const skills  = [
  { id: 1, name: "C#" },
  { id: 2, name: "C" },
  { id: 3, name: "C++" },
  { id: 4, name: "JavaScript" },
  { id: 5, name: "TypeScript" },
  { id: 6, name: "Python" },
  { id: 7, name: "Java" },
  { id: 8, name: "SQL" },
  { id: 9, name: "HTML" },
  { id: 10, name: "CSS" },
  { id: 11, name: "ASP.NET Core" },
  { id: 12, name: "ASP.NET Core Web API" },
  { id: 13, name: "ASP.NET Core MVC" },
  { id: 14, name: "Entity Framework Core" },
  { id: 15, name: "React" },
  { id: 16, name: "React Native" },
  { id: 17, name: "Flutter" },
  { id: 18, name: "iOS Development" },
  { id: 19, name: "Android Development" },
  { id: 20, name: "Angular" },
  { id: 21, name: "Vue.js" },
  { id: 22, name: "Node.js" },
  { id: 23, name: "Express.js" },
  { id: 24, name: "Django" },
  { id: 25, name: "Spring Boot" },
  { id: 26, name: "Laravel" },
  { id: 27, name: "SQL Server" },
  { id: 28, name: "PostgreSQL" },
  { id: 29, name: "MySQL" },
  { id: 30, name: "MongoDB" },
  { id: 31, name: "Redis" },
  { id: 32, name: "SQLite" },
  { id: 33, name: "Docker" },
  { id: 34, name: "Git" },
  { id: 35, name: "GitHub" },
  { id: 36, name: "REST API" },
  { id: 37, name: "GraphQL" },
  { id: 38, name: "Postman" },
  { id: 39, name: "Visual Studio" },
  { id: 40, name: "VS Code" },
  { id: 41, name: "Clean Architecture" },
  { id: 42, name: "CQRS" },
  { id: 43, name: "Repository Pattern" },
  { id: 44, name: "MVC" },
  { id: 45, name: "Microservices" },
  { id: 46, name: "SOLID Principles" },
  { id: 47, name: "Unit Testing" },
  { id: 48, name: "Integration Testing" },
  { id: 49, name: "Linux" },
  { id: 50, name: "Agile" },
  { id: 51, name: "JWT" },
  { id: 52, name: "Machine Learning" },
];


export default skills;
